apiVersion: apps/v1
kind: Deployment

metadata:
  name: config-service
  labels:
    app: config-service

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          imagePullPolicy: IfNotPresent
          image: config-service:latest
          ports:
            - containerPort: 8888
          startupProbe:
            httpGet:
              path: /health
              port: 8888
            failureThreshold: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5

