spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songintae/cloud-native-spring-in-action
          default-label: main
          search-paths: config-repo
          timeout: 5
          clone-on-start: true # 서비스 시작 시점에 원격 저장소를 미리 클론하여 빠른 응답 보장
          force-pull: true # 로컬 복사본과 원격 저장소 간 충돌 발생 시 원격 저장소를 강제로 풀하여 동기화


server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 65s
    threads:
      max: 50
      min-spare: 5
